name: discord-playing
on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy to Amazon EC2 tests
    runs-on: ubuntu-latest

    steps:
    - name: Discord Now Playing
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-agent -a /tmp/ssh_agent.sock > /dev/null
        ssh-add - <<< "${{ secrets.EC2_KEY }}"
        ssh ubuntu@ec2-18-130-229-47.eu-west-2.compute.amazonaws.com 'sudo rm -rf discord-now-playing && git clone https://github.com/npitsillos/discord-now-playing.git && cd discord-now-playing && echo TOKEN="${{ secrets.TOKEN }}" > .env && echo USERNAME="${{ secrets.USERNAME }}" >> .env && docker-compose -f docker-compose.yml up --build -d'
